# Generated by Django 2.2.7 on 2019-11-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DT', 'Детектив'), ('FN', 'Фантастика'), ('FTZ', 'Фэнтези'), ('SCF', 'Научная фантастика')], max_length=3, unique=True)),
                ('base_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='books.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='covers')),
                ('text', models.FileField(upload_to='texts')),
                ('author', models.ManyToManyField(to='books.Author')),
                ('genre', models.ManyToManyField(to='books.Genre')),
            ],
        ),
    ]
