# Generated by Django 2.2.7 on 2019-11-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191113_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='genre',
            name='base_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('DT', 'Детектив'), ('FN', 'Фантастика'), ('FTZ', 'Фэнтези'), ('SCI', 'Научная фантастика'), ('SOF', 'Социальная фантастика')], max_length=3, unique=True),
        ),
    ]
