# Generated by Django 2.2.7 on 2020-03-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200131_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='annot',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
